services:
    auth_pharmacy_node1:
      container_name: auth_pharmacy_node1
      image: kastter/pharmacy_auth:latest
      command:
        - "make"
        - "run"
      restart: always
      env_file:
        - .env
      volumes:
        - ./logs/app1:/app/logs
      networks:
        - pharmacy

    auth_pharmacy_node2:
      container_name: auth_pharmacy_node2
      image: kastter/pharmacy_auth:latest
      command:
        - "make"
        - "run"
      restart: always
      env_file:
        - .env
      volumes:
        - ./logs/app2:/app/logs
      networks:
        - pharmacy

    db:
        image: postgres:16.2
        container_name: 'auth_pharmacy_db'
        restart: always
        shm_size: 128mb
        environment:
          POSTGRES_PASSWORD: POSTGRES_PASSWORD
          POSTGRES_USER: POSTGRES_USER
          POSTGRES_DB: POSTGRES_DB
        env_file:
          - .docker.env
        volumes:
          - db:/var/lib/postgresql/data
        networks:
          - pharmacy

    nginx_auth:
      image: nginx:latest
      volumes:
        - /opt/homebrew/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - auth_pharmacy_node1
        - auth_pharmacy_node2
      networks:
        - pharmacy
        - gateway

    gateway:
      container_name: gateway
      image: nginx:latest
      volumes:
        - /opt/homebrew/etc/nginx/gateway.conf:/etc/nginx/nginx.conf  # Конфигурация для Gateway
      ports:
        - "80:80"
      depends_on:
        - nginx_auth
      networks:
        - gateway



    elasticsearch:
      container_name: elasticsearch
      image: elasticsearch:8.11.1
      ports:
        - 9200:9200
      environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
      networks:
        - gateway


    kibana:
      container_name: kibana
      image: kibana:8.11.1
      depends_on:
        - elasticsearch
      ports:
        - 5601:5601
      networks:
        - gateway

    filebeat:
      image: elastic/filebeat:8.10.0
      container_name: pharmacy_auth_filebeat
      volumes:
        - ./logs:/usr/share/filebeat/logs:ro
        - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro # :ro - read only
      depends_on:
        - elasticsearch
        - kibana
      networks:
        - gateway


volumes:
  db:
    driver: local

networks:
  pharmacy:
    driver: bridge
  gateway:
    driver: bridge
