name: "auth-pharmacy-filebeat"
logging.metrics.enabled: false
xpack.security.enabled: false
xpack.monitoring.enabled: false
setup.ilm.enabled: false
setup.template.enabled: false

filebeat.inputs:
  # замена старому log, более современный и лучше справляется
  - type: filestream
    id: filestream-logs
    scan_frequency: 1s
    enabled: true
    # Я запущу filebeat в докере и проброшу логи приложений по данному пути
    paths:
      - ./logs/app1/*.log
      - ./logs/app2/*.log
#      - /usr/share/filebeat/logs/*.log
    fields:
      service: auth-pharmacy
    fields_under_root: true

# Имя сервиса Elasticsearch в docker-compose
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "auth-pharmacy"
